export const DimensionTypes = {
  EnsemblID: 'string',
  fc: 'number',
  pValue: 'number',
  pValueNegLog10: 'number',
  FPKM: 'number',
  name: 'string',
  Name: 'string',
  biotype: 'string',
  sampleMean: 'number',
  controlMean: 'number',
  strand: 'string',
  Start: 'number',
  End: 'number',
  baseMeanSample: 'number',
  baseMeanControl: 'number',
  baseMean: 'number',
  log2FoldChange: 'number',
  lfcSE: 'number',
  stat: 'number',
  pValueAdj: 'number',
  ensembl_gene_id: 'string',
  description: 'string',
  chromosome_name: 'number',
  start_position: 'number',
  end_position: 'number',
  band: 'number',
  external_gene_name: 'string',
  external_gene_source: 'string',
  percentage_gene_gc_content: 'number',
  gene_biotype: 'string',
  source: 'string',
  version: 'string',
};

export const DefaultFilterSetting = {
  EnsemblID: '=',
  fc: '>',
  pValue: '<',
  pValueNegLog10: '<',
  FPKM: '>',
  qValue: '<',
  sampleMean: '>',
  controlMean: '>',
  name: '=',
  Name: '=',
  biotype: '=',
  strand: '=',
  Start: '>',
  End: '<',
  baseMeanSample: '<',
  baseMeanControl: '<',
  baseMean: '<',
  log2FoldChange: '<',
  lfcSE: '<',
  stat: '<',
  pValueAdj: '<',
  description: '=',
  chromosome_name: '=',
  start_position: '>',
  end_position: '>',
  band: '>',
  external_gene_name: '=',
  external_gene_source: '=',
  percentage_gene_gc_content: '>',
  gene_biotype: '=',
  source: '=',
  version: '=',
};

export default DimensionTypes;
