export const DimensionTypes = {
  EnsemblID: 'string',
  fc: 'number',
  pValue: 'number',
  pValueNegLog10: 'number',
  FPKM: 'number',
  name: 'string',
  Name: 'string',
  biotype: 'string',
  sampleMean: 'number',
  controlMean: 'number',
  strand: 'string',
  Start: 'number',
  End: 'number',
  baseMeanSample: 'number',
  baseMeanControl: 'number',
  baseMean: 'number',
  log2FoldChange: 'number',
  lfcSE: 'number',
  stat: 'number',
  pValueAdj: 'number',
};

export const DefaultFilterSetting = {
  EnsemblID: '=',
  fc: '>',
  pValue: '<',
  pValueNegLog10: '<',
  FPKM: '>',
  qValue: '<',
  sampleMean: '>',
  controlMean: '>',
  name: '=',
  Name: '=',
  biotype: '=',
  strand: '=',
  Start: '>',
  End: '<',
  baseMeanSample: '<',
  baseMeanControl: '<',
  baseMean: '<',
  log2FoldChange: '<',
  lfcSE: '<',
  stat: '<',
  pValueAdj: '<',
};

export default DimensionTypes;
